### ISSUE TITLE
Symfony DOCSのService Containerの他のページ読む

### ISSUE THREAD

**Issue by octop162** [octop162/study#7]
LearnMoreのところ
https://symfony.com/doc/current/service_container.html#learn-more

このページでは以下をみた
[How to Create Service Aliases and Mark Services as Private](https://symfony.com/doc/current/service_container/alias_private.html)
[Defining Services Dependencies Automatically (Autowiring)](https://symfony.com/doc/current/service_container/autowiring.html)

**Comment by octop162** [comment]
How to Create Service Aliases and Mark Services as Private
https://symfony.com/doc/current/service_container/alias_private.html

サービスをパブリックにする
明記しないとDIによってしかオブジェクト取得できないが明記すればメソッド経由で取得できる

```
services:
    App\Service\Foo:
        public: true
```

**Comment by octop162** [comment]
取得するときはこんな感じ

```
use App\Service\Foo;

$container->get(Foo::class);
```

ドキュメント全体的にプライベートを勧めている、最適化による速度向上やエラーに気づきやすくなるなどの利点がある。

**Comment by octop162** [comment]
プライベートにすれば直接getでアクセスできないが、エイリアスを使えばアクセスできるらしい。

**Comment by octop162** [comment]
エイリアス

サービスに別名をつけることができる。別名にpublic: trueをつけることで$container->getでオブジェクトを取得できる

```
services:
  App\Hoge:
    public: false
  app.hoge:
    alias: App\Hoge
    public: true
```

```
$container->get('app.hoge');
```

**Comment by octop162** [comment]
yamlだとショートカットも容易されている

```
services:
  app.hoge: '@App\Hoge'
```

**Comment by octop162** [comment]
エイリアスを非推奨化したい場合はdeprecatedで設定できる
メッセージがない場合はデフォルトのメッセージが使われるがmessageで明記することもできる

```
services:
  app.hoge:
    alias: 'App\Hoge'
    deprecated:
      package: 'acme/package'
      version: '1.2'
```

**Comment by octop162** [comment]
サービスを複数定義し依存関係を作る際に他のサービスから使われることを防ぎたい場合に、匿名のサービスを作ることができる。
サービスのなかで定義するため、ほかから使われずにすむ。

```
services:
    App\Foo:
        arguments:
            - !service
                class: App\AnonymousBar
```
